### ISSUE TITLE
Missing something in DDGM example 

### ISSUE THREAD

**Issue by esoreq** [jmtomczak/intro_dgm#3]
Hi, 

I might be missing a step here but in your explanation for the reparameterization trick you state the following formula 

<img src="https://render.githubusercontent.com/render/math?math=\mathbf{z}_{i} = \sqrt{1 - \beta_i} \mathbf{z}_{i-1} + \sqrt{\beta_i} \odot \epsilon">

And I can see $i$ as an argument, but I fail to see how you are using it in this function - could you explain what I missed? 
 
```python
def reparameterization_gaussian_diffusion(self, x, i):
    return torch.sqrt(1. - self.beta) * x + torch.sqrt(self.beta) * torch.randn_like(x)
```

**Comment by jmtomczak** [comment]
Hi!

Yes, that is true. In the implementation, I use the simplest version where beta_i = beta for all i=1, ..., L, i.e., we use a single value of beta. However, having beta_i, i.e., beta dependent on i, is the way to go to obtain better results.

**Comment by esoreq** [comment]
That makes sense, thanks for the quick response and thanks for this excellent resource
